# Generated by Django 3.0.2 on 2023-08-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_answer_uans_id_alter_question_uquest_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='uans_id',
            field=models.CharField(default='3c956ee92ccd', editable=False, max_length=25, null=True, verbose_name='Unique ID'),
        ),
        migrations.AlterField(
            model_name='liked',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='question',
            name='uquest_id',
            field=models.CharField(default='cc9c0f9eb8a9', editable=False, max_length=25, null=True, verbose_name='Unique ID'),
        ),
    ]
