# Generated by Django 3.0.2 on 2023-08-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20230826_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='uans_id',
            field=models.CharField(default='2b52b67963a8', editable=False, max_length=25, null=True, verbose_name='Unique ID'),
        ),
        migrations.AlterField(
            model_name='question',
            name='uquest_id',
            field=models.CharField(default='aedbcfb74c01', editable=False, max_length=25, null=True, verbose_name='Unique ID'),
        ),
    ]
